version: '3.8'

services:
  locust:
    build: .
    ports:
      - "8089:8089"
    environment:
      - LOCUST_HOST=https://www.n11.com
    volumes:
      - ./locustfile.py:/app/locustfile.py
    command: ["locust", "--host=https://www.n11.com", "--web-host=0.0.0.0"] 